# Generated by Django 5.0.1 on 2024-02-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskText', models.TextField()),
                ('taskStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
