# Generated by Django 5.0.1 on 2024-02-05 12:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('taskText', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
