# Generated by Django 5.0.1 on 2024-02-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskCategory',
            field=models.TextField(default='Fun'),
            preserve_default=False,
        ),
    ]
